/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package gb.tech

import kotlin.test.Test
import kotlin.test.assertTrue

class LibraryTest {
    @Test fun someLibraryMethodReturnsTrue() {
        val classUnderTest = Library()
        assertTrue(classUnderTest.concat("JUCA") == "MY-LIB-JUCA", "someLibraryMethod should return 'true'")
    }
}
